<a href="https://colab.research.google.com/github/Kentucky-Kaneki/Learning-Machine-Learning-/blob/main/pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
!pip install numpy

import numpy as np
import pandas as pd

In [ ]:
# row splicing [0:2] (both rows, rpw with index 2 excluded)
# column splicing [2:5] (2nd, 3rd and 4th element)

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[0:2, 2:5]

array([[ 3,  4,  5],
       [10, 11, 12]])

In [ ]:
# shape of matrix (rows, columns)

a.shape

(2, 7)

In [ ]:
# give shape of matrix to get a prefilled multidimensional np.array

a = np.ones((3,4))
b = np.zeros((2,2))
c = np.full((1,4), 4)
print("array a is: ", a)
print("array b is: ", b)
print("array c is: ", c)

array a is:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array b is:  [[0. 0.]
 [0. 0.]]
array c is:  [[4 4 4 4]]


In [ ]:
# randint(lower limt, upper limit !excluded!, shape)
np.random.randint(0, 10, (3,3))

array([[6, 7, 0],
       [2, 0, 5],
       [1, 8, 1]])

In [ ]:
# dtype (i, u, f, O, S), bytesize

arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr, arr.dtype)

arr = arr.astype("f4")
print(arr, arr.dtype)

[1 2 3 4] int64
[1. 2. 3. 4.] float32


In [ ]:
a = np.array([1,2,3,4])
print(a, "\n")
print(a + 2, "\n")
print(a - 2, "\n")
print(a * 2, "\n")
print(a / 2, "\n")
b = np.array([1,0,1,0])
print(a + b, "\n")
print(a ** 2, "\n")

A = np.ones((2,3))
print(A, "\n")
B = np.full((3,2), 2)
print(B, "\n")

# Matrix multiplication. returns error if number of A.cols != B.rows
np.matmul(A, B)

[1 2 3 4] 

[3 4 5 6] 

[-1  0  1  2] 

[2 4 6 8] 

[0.5 1.  1.5 2. ] 

[2 2 4 4] 

[ 1  4  9 16] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]] 



array([[6., 6.],
       [6., 6.]])

In [ ]:
# Series are similar to numpy arrays but have more functions and parameters when it comes to indexing

x = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523], index=[
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
])

print(x)

#splicing also works differently. the upper limit is included in series
x['France':'Japan']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
dtype: float64


France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
dtype: float64

In [ ]:
# importing data from csv, excel files etc

table = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(table.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  


In [ ]:
table.drop(columns=["longitude", "latitude"])
print(table.head())

#does not work as many numpy and pandas functions are "view" and not "copy" fns
print("\n ########################################################################### \n")
# use inplace to actually make changes instead of creating a temporary buffer

table.drop(columns=["longitude", "latitude"], inplace=True)
print(table.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  

 ########################################################################### 

   housing_median_age  total_rooms  total_bedrooms  population  households  \
0            

In [ ]:
# One function to rule them all. Get basic information regarding all the columns

table.describe()

housing_median_age   total_rooms  total_bedrooms    population  \
count         3000.000000   3000.000000     3000.000000   3000.000000   
mean            28.845333   2599.578667      529.950667   1402.798667   
std             12.555396   2155.593332      415.654368   1030.543012   
min              1.000000      6.000000        2.000000      5.000000   
25%             18.000000   1401.000000      291.000000    780.000000   
50%             29.000000   2106.000000      437.000000   1155.000000   
75%             37.000000   3129.000000      636.000000   1742.750000   
max             52.000000  30450.000000     5419.000000  11935.000000   

       households  median_income  median_house_value  
count  3000.00000    3000.000000          3000.00000  
mean    489.91200       3.807272        205846.27500  
std     365.42271       1.854512        113119.68747  
min       2.00000       0.499900         22500.00000  
25%     273.00000       2.544000        121200.00000  
50%     409.50000       3.487150        177650.00000  
75%     597.25000       4.656475        263975.00000  
max    4930.00000      15.000100        500001.00000

In [ ]:
# boolean operations return a true-false mask.
inBudget = (table["median_house_value"] < 200000)
print(inBudget)
print("\n ########################################################################### \n")
# passing a mask to a table returns only the rows where the mask is true
print(table[inBudget])

0       False
1        True
2       False
3       False
4        True
        ...  
2995    False
2996    False
2997     True
2998     True
2999    False
Name: median_house_value, Length: 3000, dtype: bool

 ########################################################################### 

      housing_median_age  total_rooms  total_bedrooms  population  households  \
1                   43.0       1510.0           310.0       809.0       277.0   
4                   19.0       1241.0           244.0       850.0       237.0   
5                   37.0       1018.0           213.0       663.0       204.0   
6                   43.0       1009.0           225.0       604.0       218.0   
7                   19.0       2310.0           471.0      1341.0       441.0   
...                  ...          ...             ...         ...         ...   
2989                32.0       1295.0           295.0      1097.0       328.0   
2990                49.0       1638.0           456.0      1500.0 